apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  namespace: openfaas-fn
spec:
  template:
    spec:
      containers:
      - name: psql
        image: postgres:latest
        command: ["sh", "-c", "psql -h db -U users -d usersDb -f /sql/init.sql"]
        env:
        - name: PGPASSWORD
          value: password
        volumeMounts:
        - name: sql-volume
          mountPath: /sql
      restartPolicy: Never
      volumes:
      - name: sql-volume
        configMap:
          name: init-sql
  backoffLimit: 4
