version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

custom:
  defaultCors:
    origin: "*"
headers:
  - Content-Type
  - X-Amz-Date
  - Authorization
  - X-Api-Key
  - X-Amz-Security-Token
  - X-Amz-User-Agent

functions:
  gen-user:
    lang: python3-http
    handler: ./gen-user
    image: lizaa28/gen-user:latest
    secrets:
      - fernet-key

  auth-user:
    lang: python3-http
    handler: ./auth-user
    image: lizaa28/auth-user:latest
    secrets:
      - fernet-key

  renew-user:
    lang: python3-http
    handler: ./renew-user
    image: lizaa28/renew-user:latest
    secrets:
      - fernet-key


