version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: usersDb
      POSTGRES_USER: users
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer:latest
    depends_on:
      - db
    ports:
      - "8081:8080"
    

#volumes:
  #postgres-user-data:

