version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112

functions:
  gen-user:
    lang: python3-http
    handler: ./gen-user
    image: mohamedbenmaouche09/gen-user:latest
    secrets:
      - fernet-key

  auth-user:
    lang: python3-http
    handler: ./auth-user
    image: mohamedbenmaouche09/auth-user:latest
    secrets:
      - fernet-key

  renew-user:
    lang: python3-http
    handler: ./renew-user
    image: mohamedbenmaouche09/renew-user:latest
    secrets:
      - fernet-key
