version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112

functions:
  gen-user:
    lang: python3-flask
    handler: ./gen-user
    image: localhost:5000/gen-user:latest
    secrets:
      - fernet-key

  auth-user:
    lang: python3-flask
    handler: ./auth-user
    image: localhost:5000/auth-user:latest
    secrets:
      - fernet-key

  renew-user:
    lang: python3-flask
    handler: ./renew-user
    image: localhost:5000/renew-user:latest
    secrets:
      - fernet-key
